# Generated by Django 4.0.2 on 2022-02-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('completion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_subject', models.CharField(max_length=30)),
                ('details', models.TextField(max_length=500)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(blank=True)),
                ('tasks_status', models.CharField(choices=[('N', 'New'), ('I', 'In_Progress'), ('C', 'Completed')], max_length=1)),
                ('severity', models.CharField(choices=[('H', 'High'), ('L', 'Low')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
